# Generated by Django 4.2.16 on 2024-09-13 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
