version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  django:
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A event_manager worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django

  celery_beat:
    build: .
    command: celery -A event_manager beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
